manifest:
  defaults:
    remote: rose

  remotes:
    - name: rose
      url-base: https://github.com/rose-project
    - name: openembedded
      url-base: https://git.openembedded.org

  projects:
    - name: bitbake
      path: tools/bitbake
      remote: openembedded
      revision: "10118785e4a670bce4980e1044c0888a8b6e84af" # 2.8
      clone-depth: 1
    - name: openembedded-core
      path: layers/openembedded-core
      remote: openembedded
      revision: "a1f4ae4e569bc0e36c27c1e4651e502e54d63b28" # scarthgap
      clone-depth: 1
    - name: meta-openembedded
      path: layers/meta-openembedded
      remote: openembedded
      revision: "ec0469748be4159fb83fb0fa0148d786484c88cf" # scarthgap
      clone-depth: 1
    - name: meta-rose
      path: layers/meta-rose
      remote: rose
    - name: meta-raspberrypi-bsp
      path: layers/meta-raspberrypi-bsp
      remote: rose

  self:
    path: config
